inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false

target 'LinkusDemo (iOS)' do
platform :ios, '11.0'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'Toast', '~> 4.0.0'
    pod 'YYCategories', '~> 1.0.4'
    pod 'HWPanModal', '~> 0.8.9'
    pod 'Masonry', '~> 1.1.0'
    pod 'ReactiveObjC', '~> 3.1.1'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
    pod 'linkus-sdk', '~> 1.0.12'
end

target 'LinkusDemo (macOS)' do
platform :osx, '10.13'
#    pod 'WCDBSwift'
#    pod 'ObjectMapper'
#    pod 'SDWebImageSwiftUI'
    pod 'linkus-sdk-MacOS', '~> 1.0.12'
end
