inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false
use_frameworks!

target 'LinkusDemo (iOS)' do
platform :ios, '11.0'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'Toast', '~> 4.0.0'
    pod 'YYCategories', '~> 1.0.4'
    pod 'HWPanModal', '~> 0.8.9'
    pod 'Masonry', '~> 1.1.0'
    pod 'ReactiveObjC', '~> 3.1.1'
    pod 'OpenSSL-Universal', '~> 1.0.2.20'
#    pod 'linkus-vivo', '0.0.18'
end

target 'LinkusDemo (macOS)' do
platform :osx, '10.13'
    pod 'OpenSSL-Universal', '~> 1.0.2.20'
#    pod 'WCDBSwift'
#    pod 'ObjectMapper'
#    pod 'SDWebImageSwiftUI'
#    pod 'linkus-vivo-MacOS', '~> 0.0.18'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end
